- type: button
  text: 00-ServerIdCenter
  script: /home/ubuntu/Projects/try_auto_deploy/00-s_server_id_center.py -o test_assets/server.override/ts_tm.yaml
  row: 0
  column: 0
  
- type: button
  text: 01-ConfigCenter
  script: /home/ubuntu/Projects/try_auto_deploy/01-s_config_center.py -o test_assets/server.override/ts_tm.yaml
  row: 0
  column: 1
  
- type: button
  text: 02-ServerList
  script: /home/ubuntu/Projects/try_auto_deploy/02-s_server_list.py -o test_assets/server.override/ts_tm.yaml
  row: 0
  column: 2

- type: button
  text: 09-RelayInfoDispatcher
  script: /home/ubuntu/Projects/try_auto_deploy/09-s_relay_info_dispatcher.py -o test_assets/server.override/ts_tm.yaml
  row: 1
  column: 0 

- type: button
  text: 10-DeviceRelay
  script: /home/ubuntu/Projects/try_auto_deploy/10-s_device_relay.py -o test_assets/server.override/ts_tm.yaml
  row: 1
  column: 1 


- type: button
  text: 11-s_device_state_relay
  script: /home/ubuntu/Projects/try_auto_deploy/11-s_device_state_relay.py -o test_assets/server.override/ts_tm.yaml
  row: 1
  column: 2

  
  
- type: button
  text: 12-AuthServer
  script: /home/ubuntu/Projects/try_auto_deploy/12-s_auth_cache.py -o test_assets/server.override/ts_tm.yaml
  row: 1
  column: 3 

- type: button
  text: 15-s_pa
  script: /home/ubuntu/Projects/try_auto_deploy/15-s_pa.py -o test_assets/server.override/ts_tm.yaml
  row: 1
  column: 4 

- type: button
  text: 16-s_device_selector_dispatcher
  script: /home/ubuntu/Projects/try_auto_deploy/16-s_device_selector_dispatcher.py -o test_assets/server.override/ts_tm.yaml
  row: 1
  column: 5 

- type: button
  text: 17-s_device_selector
  script: /home/ubuntu/Projects/try_auto_deploy/17-s_device_selector.py -o test_assets/server.override/ts_tm.yaml
  row: 1
  column: 6 

- type: button
  text: 80-r_device_audit_to_backend
  script: /home/ubuntu/Projects/try_auto_deploy/80-r_device_audit_to_backend.py -o test_assets/server.override/ts_tm.yaml
  row: 8
  column: 0

- type: button
  text: 98-ServerListDownloader
  script: /home/ubuntu/Projects/try_auto_deploy/98-t_server_list_downloader.py -o test_assets/server.override/ts_tm.yaml
  row: 9
  column: 0

- type: button
  text: 99-AddressTest
  script: /home/ubuntu/Projects/try_auto_deploy/99-s_address_test.py -o test_assets/server.override/ts_tm.yaml
  row: 9
  column: 1
    
- type: button
  text: A0-X-Device
  script: /home/ubuntu/Projects/try_auto_deploy/a0-x_device.py -o test_assets/server.override/ts_tm.yaml
  row: 10
  column: 0
    